# Generated by Django 5.2.5 on 2025-08-31 06:46

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[800, 600], upload_to='about/')),
                ('firstservice', models.CharField(max_length=255, verbose_name='1-xizmat nomi')),
                ('serviceabout1', models.TextField(verbose_name='1-xizmat haqida')),
                ('secondservice', models.CharField(max_length=255, verbose_name='2-xizmat nomi')),
                ('serviceabout2', models.TextField(verbose_name='2-xizmat haqida')),
                ('thirdservice', models.CharField(max_length=255, verbose_name='3-xizmat nomi')),
                ('serviceabout3', models.TextField(verbose_name='3-xizmat haqida')),
            ],
            options={
                'verbose_name': 'Kompaniya haqida',
                'verbose_name_plural': 'Kompaniya haqida ',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.FileField(upload_to='banner/')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name_plural': 'Contact ',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Manzil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Telefon raqam')),
            ],
            options={
                'verbose_name': 'Manzil, telefonraqam, address',
                'verbose_name_plural': 'Manzil, telefonraqam, address ',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('type', models.CharField(max_length=100, verbose_name='Turi')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('star', models.PositiveSmallIntegerField(default=0, verbose_name='Yulduzlar soni')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[300, 300], upload_to='customers/')),
            ],
            options={
                'verbose_name': 'Mijozlar fikrlari',
                'verbose_name_plural': 'Mijozlar fikrlari ',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('is_top', models.BooleanField(default=False, verbose_name='Eng yuqorida chiqarilsinmi?')),
            ],
            options={
                'verbose_name': 'Savollar va Javoblar',
                'verbose_name_plural': 'Savollar va Javoblar ',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('logo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[200, 200], upload_to='footer/')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoqlar va hokazo',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar va hokazo ',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='main/')),
                ('icon', models.FileField(upload_to='icons/')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
            ],
            options={
                'verbose_name': 'Asosiy sahifa',
                'verbose_name_plural': 'Asosiy sahifa ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[600, 600], upload_to='products/')),
                ('title', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('status', models.CharField(max_length=50, verbose_name='Holati')),
                ('star', models.PositiveSmallIntegerField(default=0, verbose_name='Yulduzlar soni')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='O‘lchami')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 600], upload_to='products/')),
                ('image_3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 600], upload_to='products/')),
                ('image_4', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 600], upload_to='products/')),
                ('image_5', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 600], upload_to='products/')),
                ('image_6', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 600], upload_to='products/')),
                ('extra_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[600, 600], upload_to='products/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Mahsulotlar',
                'verbose_name_plural': 'Mahsulotlar ',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('img', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[1920, 600], upload_to='slider/')),
            ],
            options={
                'verbose_name': 'Aylanuvchi rasmlar',
                'verbose_name_plural': 'Aylanuvchi rasmlar ',
            },
        ),
    ]
