# Generated by Django 5.2.5 on 2025-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.FileField(upload_to='banner/')),
            ],
            options={
                'verbose_name': 'Sotuv banneri',
                'verbose_name_plural': 'Sotuv banneri',
            },
        ),
    ]
