# Generated by Django 5.2.5 on 2025-08-31 15:06

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='products/'),
        ),
    ]
