# Generated by Django 5.2.5 on 2025-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_alter_product_extra_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.FileField(upload_to='background_image/')),
                ('video_url', models.CharField(max_length=100000)),
            ],
            options={
                'verbose_name': 'Orqa fon videosi',
                'verbose_name_plural': 'Orqa fon videosi',
            },
        ),
    ]
