# Generated by Django 5.2.5 on 2025-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Ranglar',
                'verbose_name_plural': 'Ranglar',
            },
        ),
    ]
