# Generated by Django 5.2.5 on 2025-09-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0006_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='mebel.colors', verbose_name='Mavjud ranglar'),
        ),
    ]
