# Generated by Django 5.2.5 on 2025-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0007_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='mebel.colors', verbose_name='Mavjud ranglar'),
        ),
    ]
